#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Account;
use Socialtext::System qw/shell_run/;
use Memoize qw/unmemoize/;

# We need to re-load the list of plugins after we install marketo,
# so un-memoize this function.
unmemoize('Socialtext::Pluggable::Adapter::plugins');

if ($>) {
    print "Not running as root - skipping marketo plugin install.\n";
}
else {
    print "Installing the Marketo plugin\n";
    shell_run("st-appliance-install-plugin marketo");
}

my $accts = Socialtext::Account->All(
    order_by => 'name',
    type => 'Free 50',
);
while (my $acct = $accts->next) {
    print "Enabling marketo for: " . $acct->name . "\n";
    $acct->enable_plugin('marketo');
}
exit 0;
