#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Migration::Utils qw/create_job_for_each_workspace create_job/;

create_job_for_each_workspace('ReIndexWorkspace');

create_job('SwitchToSolr');

exit 0;
