#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
BEGIN { push @INC, "$ENV{ST_CURRENT}/nlw/lib" if $ENV{ST_CURRENT} }
use Plack::Runner;
use FindBin;
my $psgi = "$FindBin::Bin/nlw.psgi";
die "Cannot find $psgi" unless -e $psgi;

# Plack::Handler::Starman::Socialtext uses this:
$::proctitle = 'nlw-psgi';

use Socialtext::Daemontools;
Socialtext::Daemontools->RunSupervised(
    log_file => "nlw-psgi/error.log",
    port_name => 'backend_http_port',
    cb => sub {
        my $port = shift;
        $0 = $::proctitle;
        my $runner = Plack::Runner->new;
        my @argv = (
            '--server'       => 'Starman::Socialtext',
            '--workers'      => 5,
            '--host'         => 'localhost',
            '--listen'       => "127.0.0.1:$port",
            '--listen'       => "127.0.0.1:".($port+1000), # backend_https_port
            '--env'          => 'development',
            '--reload'       => 1,
            '--app'          => $psgi,
        );
        $runner->parse_options(@argv);
        $runner->set_options(argv => \@argv);
        $runner->run;
    }
);

