#!/usr/bin/perl
# @COPYRIGHT@

use strict;
use warnings;
use Socialtext::Group;


print "Creating GroupIndex jobs ...\n";
my $jobs = Socialtext::Group->IndexGroups();
print "Done - created $jobs jobs.\n";
