index_title: Socialtext Javascript Testing
import_libs:
  - ../../common/javascript/jquery-1.2.6.js
  - ../../s2/javascript/loc.js 
  - ../../s2/javascript/Cookie.js
  - ../../common/javascript/prototype-1.4.0/dist/prototype.js
  - ../../common/javascript/WebToolkit-base64-2007-09-25.js
  - ../../common/javascript/Ajax-0.11/lib/Ajax.js
  - ../common/lib/Test/Wikiwyg.js
  - ../../s2/javascript/main.js
  - ../../s2/javascript/md5.js
  - ../../s2/javascript/Cookie.js
  - ../../s2/javascript/pageview.js
  - ../../common/javascript/DOM.Events-0.02/lib/DOM/Events.js
  - ../../common/javascript/YAML-0.11/lib/YAML.js
  - ../../common/javascript/Widget.Lightbox-0.06/lib/Widget/Lightbox.js
  - ../../common/javascript/Wikiwyg-2007-07-17/lib/Wikiwyg.js
  - ../../common/javascript/Wikiwyg-2007-07-17/lib/Wikiwyg/Wysiwyg.js
  - ../../s2/javascript/Wikiwyg/Socialtext.js
  - ../../s2/javascript/Widgets.js 
  - ../../s2/javascript/Wikiwyg/Widgets.js
  - ../../s2/javascript/Wikiwyg/Wikitext/Socialtext.js
  - ../../s2/javascript/Debug.js
