index_title: Socialtext Visual JavaScript Testing
import_libs:
  - ../../common/javascript/jquery-1.2.6.js
  - ../../common/javascript/YAML-0.11/lib/YAML.js
  - ../../s2/javascript/Debug.js
  - ../common/lib/Test/Visual.js
