#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::SQL qw/sql_execute/;

my $sth = sql_execute(q{
    SELECT account_id, all_users_workspace FROM "Account"
        WHERE all_users_workspace IS NOT NULL
    });
my $ids = $sth->fetchall_arrayref;

for my $row (@$ids) {
    my $acct = Socialtext::Account->new(account_id => $row->[0]);
    die "Can't find account_id: $row->[0]" unless $acct;
    my $auw  = Socialtext::Workspace->new(workspace_id => $row->[1]);
    die "Can't find workspace_id $row->[1]" unless $auw;

    $auw->add_account(account => $acct);

    sql_execute(q{
        UPDATE "Account" 
            SET all_users_workspace TO NULL
            WHERE account_id = ?
        }, $acct->account_id,
    );
}

exit 0;
