#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;

use Socialtext::Migration::Utils qw/create_job_for_each_account/;

create_job_for_each_account('SaveOldDefaultDashboard');
create_job_for_each_account('CreateCentralWorkspace', undef, not_upgrade => 1);

exit 0;

