#!/usr/bin/perl
# @COPYRIGHT@
use warnings;
use strict;
use lib 'lib';
use Socialtext::SQL qw/get_dbh/;
use Socialtext::UserSet qw/:const/;
use Test::More tests => 10;

my $dbh = get_dbh();
local $dbh->{RaiseError} = 1;

my ($mig_state) = $dbh->selectrow_array(qq{
    SELECT value FROM "System" WHERE field = 'migration-56'
});
is $mig_state, 4, "all phases of the migration completed";

my @tables = qw(
   user_account_role
   group_account_role
   group_workspace_role
   user_group_role
   user_workspace_role
);

# Make sure that all non-affiliate roles have been deleted.
for my $table (@tables) {
    my ($count) = $dbh->selectrow_array(qq{
        SELECT COUNT(1) FROM $table
        WHERE role_id NOT IN (
            SELECT role_id FROM "Role" WHERE name = 'affiliate' LIMIT 1
        )
    });
    is $count, 0, "role entries for $table all migrated";
}

my %to_check = (
    user => {
        table      => '"UserMetadata"',
        id_column  => 'user_id',
        account_id => 'primary_account_id',
        set_id_col => 'user_id',
    },
    group => {
        table      => 'groups',
        id_column  => 'group_id',
        account_id => 'primary_account_id',
        set_id_col => 'user_set_id',
    },
    workspace => {
        table      => '"Workspace"',
        id_column  => 'workspace_id',
        account_id => 'account_id',
        set_id_col => 'user_set_id',
    }
);

# Ensure all Users/Groups/Workspaces have role `member` in their Primary
# Account
for my $thing (keys %to_check) {
    my $meta = $to_check{$thing};
    my $sql = qq{
        SELECT COUNT(DISTINCT pacct.$meta->{id_column})
          FROM $meta->{table} pacct
         WHERE pacct.$meta->{account_id} NOT IN (
            SELECT into_set_id - }.PG_ACCT_OFFSET.qq{
              FROM user_set_include
             WHERE from_set_id = pacct.$meta->{set_id_col}
               AND into_set_id }.PG_ACCT_FILTER.qq{
               AND role_id IN (SELECT role_id FROM "Role" WHERE name = 'member')
         )
    };
    my ($count) = $dbh->selectrow_array($sql);
    is $count, 0,
        "all ${thing}s have a direct member role in their primary account";
}

# Ensure that there are no 'affiliate' roles in the user_set_include table.
my ($count) = $dbh->selectrow_array(q{
    SELECT COUNT(1)
      FROM user_set_include
     WHERE role_id IN (
        SELECT role_id FROM "Role" WHERE name = 'affiliate'
    )
});
is $count, 0, "no 'affiliate' roles found";

exit 0;
