#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::SQL qw/sql_execute/;

sql_execute(q{
    DELETE FROM profile_relationship
    WHERE NOT shares_account(user_id, other_user_id)
});
