#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::System qw/shell_run/;

if ($>) {
    print "Not running as root - skipping like plugin install.\n";
}
else {
    print "Installing the like plugin\n";
    shell_run("st-appliance-install-plugin like");
}

shell_run("st-admin enable-plugin --all-accounts --plugin like");

exit 0;
