#!/bin/bash
# @COPYRIGHT@

if [ -d /usr/share/nlw/plugin/widgets ]; then
    st-run-as-web-user st-widgets update-all --ceqlotron --force --verbose
    st-run-as-web-user st-widgets update-gallery --verbose || true
fi
