#!/bin/bash
# @COPYRIGHT@

if [ -d /usr/share/nlw/plugin/widgets ]; then
    st-run-as-web-user st-widgets purge-jobs
    st-run-as-web-user st-widgets update-all --force --verbose
    st-run-as-web-user st-widgets update-gallery --force --verbose || true
fi
