#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::File qw/set_contents/;
use Socialtext::System qw/shell_run/;

set_contents('/etc/default/apache2' => "NO_START=1\n");

# TODO: Migrate /etc/apache2/conf.d/hostname.conf


print "Stopping Apache2, then starting nginx ...\n";
shell_run("/etc/init.d/apache2 stop");
shell_run("/etc/init.d/nginx start");

exit 0;
