#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::System qw/shell_run/;
use Socialtext::Migration::Utils qw/create_job/;

# turn off explorer link
shell_run('st-appliance-set-config explore_is_public 0');

# create a monitoring job
create_job('MakeExplorePublic', -30);

exit 0;
