#!/usr/bin/env perl
# @COPYRIGHT@

use strict;
use warnings;
use Socialtext::Resting::Getopt qw/get_rester/;
use Getopt::Long;

my $port = $> + 20000;
my $r = get_rester();
$r->server("http://localhost:$port") unless $r->server;
$r->username('devnull1@socialtext.com') unless $r->username;
$r->password('d3vnu11l') unless $r->password;

my %args;
GetOptions( \%args,
    'class=s',
    'url=s',
    'account-id=s',
    'workspace-id=s',
) or usage();

usage() unless %args;


$args{account_id} = delete $args{'account-id'} if $args{'account-id'};
$args{workspace_id} = delete $args{'workspace-id'} if $args{'workspace-id'};

print "Setting webhook on " . $r->server . "\n";
$r->put_webhook( %args );
print $r->response->status_line, "\n";

exit;

sub usage {
    die <<EOT
USAGE: $0 --class=foo --url=foo

--account-id=foo
--workspace-id=foo
EOT
}
