#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use App::Daemon qw/daemonize/;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::System qw/shell_run/;
use Socialtext::Paths;
use Socialtext::AppConfig;

my $sdir = 
    "$FindBin::Bin/../../appliance/libsocialtext-appliance-perl/service";

die "Can't find service directory: $sdir" unless -d $sdir;
die "Service directory has no run: $sdir" unless -e "$sdir/run";

# Get App::Daemon to parse the command line, so we can act on it
App::Daemon::cmd_line_parse();

# Stopping "supervise" needs special handling; can't be done via App::Daemon
if ($App::Daemon::action eq 'stop') {
    shell_run("-svc -d -x $sdir");
    exit;
}

print "Starting supervise on $sdir\n" unless ($App::Daemon::action eq 'status');

$App::Daemon::logfile = Socialtext::Paths::log_directory() . '/supervise.log';
$App::Daemon::pidfile = Socialtext::AppConfig->pid_file_dir . '/supervise.pid';
daemonize();

shell_run("supervise $sdir");
