#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use Cwd qw(cwd);
use lib "$FindBin::Bin/../lib";
use Socialtext::MakeJS;
use Getopt::Long qw(GetOptions);

$Socialtext::MakeJS::VERBOSE = 1;

my $usage = "USAGE: $0 <all|clean|target>\n";
my %opts;
GetOptions(\%opts, qw(skin=s all-skins));
my $target = shift || 'all';

if ($opts{'all-skins'}) {
    Socialtext::MakeJS->BuildAllSkins;
}
else {
    unless ($opts{skin}) {
        ($opts{skin}) = cwd =~ m{skin/([^/]+)/javascript$};
        die "Not in a skin dir\n" unless $opts{skin};
    }
    Socialtext::MakeJS->Build($opts{skin}, $target);
}

