#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::MakeJS;

my $usage = "USAGE: $0 <build|clean> [skin] [target]\n";

my $command = shift || die $usage;
my $skin = shift;
my $target = shift;

$Socialtext::MakeJS::VERBOSE = 1;

if ($command eq 'build') {
    if ($skin) {
        if ($target) {
            Socialtext::MakeJS->Build($skin, $target);
        }
        else {
            Socialtext::MakeJS->BuildSkin($skin);
        }
    }
    else {
        Socialtext::MakeJS->BuildAllSkins;
    }
}
elsif ($command eq 'clean') {
    if ($skin) {
        Socialtext::MakeJS->CleanSkin($skin);
    }
    else {
        Socialtext::MakeJS->CleanAllSkins($skin);
    }
}
else {
    die "Unknown command: $command\n";
}
