#!/usr/bin/perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Cwd qw(cwd);
use Socialtext::MakeJS;
use Time::HiRes qw(time);

$Socialtext::MakeJS::VERBOSE = 1;

my $code_base = Socialtext::AppConfig->code_base;
(my $dir = cwd) =~ s{^$code_base/}{};
$dir =~ s{^$ENV{ST_CURRENT}/plugins}{plugin};

my @targets = @ARGV ? @ARGV : ('all');
my $before = time;
for my $target (@targets) {
    if ($target eq 'all') {
        Socialtext::MakeJS->BuildAll;
    }
    elsif ($target eq 'clean') {
        Socialtext::MakeJS->CleanDir($dir);
    }
    else {
        Socialtext::MakeJS->Build($dir, $target);
    }
}
my $lapsed = (time - $before);
warn "Took $lapsed seconds.\n";
