#!/usr/bin/env perl
use 5.12.0;
use List::Util 'max';

die "Usage: $0 input.po > output.po\n" unless @ARGV;

my $msgid;
my @params;

sub words {
    my $text = shift;
    $text =~ s/<[^>]*//g;
    $text =~ s/&\w+;//g;
    return map { s/_/-/; s/^-//; s/-$//; lc $_ } grep {
        not($_ ~~ [qw[a an the]]);
    } grep /\w/, split(/\W+/, $text);
}

for (<>) {
    when (/msgid "(.*)"/) {
        print;
        my $max;
        $msgid = join '-', map { if (/^\d$/) { $max = max($max, $_); () } else { $_ } } words $1;
        if ($max) {
            push @params, (('XXX') x $max);
            $msgid .= "=" . join(',', @params[0..$max-1]);
        }
    }
    when (/#\. \((.*)\)/) {
        @params = words $1;
        print;
    }
    when (/msgstr "(.*)"/) {
        if ($1 eq '') {
            my $section = 'XXX';
            say qq[msgstr "$section.$msgid"];
        }
        else {
            print;
        }
        @params = ();
    }
    default {
        print;
    }
}
