#!/usr/bin/env perl
use 5.12.0;
use autodie;
use open qw(:std :utf8);
use Getopt::Long;
use FindBin '$RealBin';
use lib "$RealBin/../lib";
use Socialtext::l10n::DevUtils;

my ($in, $out);
for my $txt (@ARGV) {
    open $in, '<', $txt;
    my $out_file = $txt;
    $out_file =~ s/\.txt\b//;
    open $out, '>', "$out_file.po";
    select $out;

    local $/ = '[[[';
    while (<$in>) {
        s/\r//g;
        s/\n+$//;
        s/"/\\"/g;
        s/^/msgid "/;
        s/\]\]\]\s*/"\nmsgstr "/;
        s/\s*\[\[\[\s*/"\n\n/;
        print;
    }
    print qq["\n];

    close $in;
    close $out;
    warn "*** $txt.po\n";
}
