#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use Fatal qw/chdir symlink/;
use lib "$FindBin::Bin/../lib";
use Socialtext::System qw/shell_run/;

my $reports_dir = "$FindBin::Bin/../../socialtext-reports";
unless (-d $reports_dir) {
    die "Couldn't find reports directory at $reports_dir!\n";
}

unless (-l "lib/Socialtext/Reports") {
    symlink "$reports_dir/lib/Socialtext/Reports" => "lib/Socialtext/Reports";
}

unless (-l "lib/Socialtext/WikiFixture/Reports.pm") {
    symlink "$reports_dir/lib/Socialtext/WikiFixture/Reports.pm" =>
        "lib/Socialtext/WikiFixture/Reports.pm";
}

chdir $reports_dir;
shell_run("./setup-dev-env");
