#!/usr/bin/env perl

use 5.12.0;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Test::Socialtext::DotProve qw(load save);

my @files  = @ARGV;
my $target = pop @files;

my $into = load($target);
foreach my $file (@files) {
    my $from = load($file);
    while (my ($k, $v) = each %{$from->{tests}}) {
        my $from_fail = $v->{last_fail_time};
        my $into_fail = $into->{tests}->{$k}->{last_fail_time};

        if ($from_fail > $into_fail) {
            $into->{tests}->{$k} = $v;  # keep most recent fail timestamp
        }
    }
}

save($into, $target);
