#!/bin/bash

PG_HBA=/etc/postgresql/9.0/main/pg_hba.conf
if [ ! -e "$PG_HBA" ]; then
    echo "Usage: $0"
    echo "$PG_HBA does not exist."
    exit 1
fi

BEFORE=`md5sum $PG_HBA | awk '{print $1}'`
cat - <<PG_HBA > $PG_HBA
# Socialtext Postgres Configuration
local   all       postgres    ident
local   NLW       nlw         trust
local   template1 nlw         trust
local   sameuser  all         ident
PG_HBA
AFTER=`md5sum $PG_HBA | awk '{print $1}'`

if [ "$BEFORE" != "$AFTER" ]; then
    echo "$PG_HBA changed.  Restarting PostgreSQL $VER"
    /etc/init.d/postgresql restart
fi
