#!/usr/bin/perl
use strict;
use warnings;
use LWP::Simple qw/get/;
use lib 'lib';
use Socialtext::String;
use Getopt::Long;

my $fl = '*';
GetOptions(
    'fl:s' => \$fl,
);

my $query = shift;
die "USAGE: $0 <query_term>" unless $query;
$query = Socialtext::String::uri_escape($query);
$fl = Socialtext::String::uri_escape($fl);

my $url = "http://localhost:8983/solr/$ENV{USER}/select?q=QUERY&rows=20&wt=json&indent=true&fl=$fl&hl=false";

$url =~ s/QUERY/$query/;

my $results = get($url);

print "$results\n";

