#!/usr/bin/perl
use warnings;
use strict;

use Socialtext::MLDBMAccess;
use YAML qw/DumpFile LoadFile/;

use Getopt::Long;

my $restore = 0;
GetOptions(
	'restore!' => \$restore
        'help' => \&usage;
);
my $from = shift;
my $to = shift;

if ($restore) {
	$from ||= 'attachments.yaml';
	$to ||= 'attachments.db';
        usage() unless -f $from;
	my $yaml = LoadFile($from);
	my $db = Socialtext::MLDBMAccess::tied_hashref(filename=>$to, writing=>1);
	%$db = %$yaml;
	undef $db;
}
else {
	$from ||= 'attachments.db';
	$to ||= 'attachments.yaml';
        usage() unless -f $from;
	my $db = Socialtext::MLDBMAccess::tied_hashref(filename=>$from, writing=>0);
	DumpFile($to, \%$db);
}

exit 0;

sub usage {
    print <<USAGE
USAGE: $0 my.db my.yaml
       $0 --restore my.yaml my-new.db

Copies database files in MLDBM format to (or from) YAML.

USAGE
}
